version: "3.7"
services:
    turl:
        image: turl
        networks:
            - turl-services-network
        build:
            dockerfile: Dockerfile
            context: .
        restart: "no"
        volumes:
            - ./secrets:/secrets
        command: ["python3", "-m", "unittest"]

networks:
    turl-services-network:
        name: turl-services-network
