version: "3.7"
services:
    zookeeper:
        image: 'bitnami/zookeeper:3'
        restart: 'no'
        networks:
            - turl-services-network
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    kafka-node:
        image: 'bitnami/kafka:2'
        restart: 'no'
        networks:
            - turl-services-network
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
        depends_on:
            - zookeeper

networks:
    turl-services-network:
        name: turl-services-network
        external: true
